# https://docs.docker.com/compose/compose-file
# docker-compose up -d
# docker-compose ps
# docker-compose stop
# docker-compose down
# https://levelup.gitconnected.com/creating-and-filling-a-postgres-db-with-docker-compose-e1607f6f882f

version: '3.7'
services:
    postgres:
        image: postgres:11.1-alpine
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        container_name: postgres
        ports:
          - '5432:5432'