# https://github.com/Huachao/vscode-restclient
@customers-api=http://localhost:8000
@contentType = application/json

###
# @name ApiRoot
GET {{customers-api}}
###

###
# @name Get_All_Customers
@page=1
@pageSize=10
GET {{customers-api}}/api/v1/customers?Page={{page}}&PageSize={{pageSize}}
accept: application/json
Content-Type: application/x-www-form-urlencoded
###

###
# @name Get_Customer_By_Id
@customer_id=701835906383872
GET https://localhost:8001/api/v1/customers/{{customer_id}}
accept: application/json
Content-Type: application/x-www-form-urlencoded
###

